### PR TITLE
Append api urls with /api/

### PR DESCRIPTION
**Pull request by sheoranjs24**
Solves issue #101 
- All REST API (backend) URLs are now prefixed with '/api/'.
- Changed front-end code to reflect the new URLs.
- Nginx listens to local port 8002 for user testing. (I changed the port from 8000 to 8002 to avoid port bind if someone wants to use `python manage.py runserver`.
- Added bin/nginx.conf. We can now locally check if nginx config is working. To test locally:
  - Install nginx
  - Create symbolic link for nginx.conf to nginx directory:  
    `ln -s beLocal/bin/nginx.conf /etc/nginx/sites-enabled/beLocal.conf`  [ For mac nginx directory is: /usr/local/etc/nginx/sites-enabled/beLocal.conf']
  - Run nginx server:   `sudo nginx start`  [ For mac: `sudo nginx` ]
  - Run gunicorn:  `sudo gunicorn server.wsgi:application --bind=localhost:8001`

For deployment:
- Ignore ngnix.conf file  (i.e. don't symlink it to nginx directory). We already have a working config file.
- Change file src/client/api/scripts/services/stateservice.js, line 318  `return 'https://belocalvictoria.me/api/';` 

If everything is working fine:
- remove '@django' from nginx config file `location \ { try_files $uri $uri/index.html @django; }`

### CODE REVIEW

**Comment by scottlow** [comment]
@sheoranjs24 Sorry it took me so long to get to this! I've been pretty busy, and have just been picking away at protractor test cases when I have spare moments. 

Since @CakeBrewery is our deployment person, I'll get him to look this over as well, but everything looks good

**Comment by CakeBrewery** [comment]
Noted. I can't go over it today but I will take a look. Thanks for doing
this, it looks good

**Comment by CakeBrewery** [comment]
The symbolic link should be `ln -s beLocal/bin/nginx.conf /etc/nginx/sites-enabled/beLocal.conf`
enable => enabled. (Note that the first path must be absolute on Linux machines) 

Also, inside your nginx.conf you have various paths that are specific to your file organization that everyone using this Nginx configuration might want to change according to theirs. 

The Nginx configuration seems to be good but I still have a TON of client-side and Django bugs that started occurring recently. I am not sure if these are specific to my machines and/or related to this branch but if it works with Scott's I think it should be ok.

**Comment by sheoranjs24** [comment]
Thanks sam for pointing out the correct folder path. 
And yes one must make sure that the paths in nginx.conf file reflects the real paths in their system.

**Pull request merged**
